import { MirrorWord } from "./utils";

/**
 * Ref: https://github.com/danielmiessler/SecLists/tree/master/Pattern-Matching
 * Ref: https://book.hacktricks.xyz/pentesting-web/ssti-server-side-template-injection/el-expression-language
 */

const DefaultKeywords = [
  //,
  "['$regex']",
  '["$regex"]',
  "[$regex]",
  '"$regex"',
  "'$regex'",
  "['$ne']",
  '["$ne"]',
  "[$ne]",
  '"$ne"',
  '"$ne"',
  '["$where"]',
  "['$where']",
  "[$where]",
  '"$where"',
  '"$where"',
  //,
  "password=%s",
  "}, { password : /.*/ }",
  "password : /.*/",
  "password[$regex]",
  'password["$regex"]',
  "password['$regex']",
  'password:{"$regex"',
  "password:{'$regex'",
  '"password":{"$regex"',
  "'password':{'$regex'",
  "password[$ne]",
  'password["$ne"]',
  "password['$ne']",
  'password:{"$ne"',
  "password:{'$ne'",
  '"password":{"$ne"',
  "'password':{'$ne'",
  "password[$gt]",
  'password["$gt"]',
  "password['$gt']",
  'password:{"$gt"',
  "password:{'$gt'",
  '"password":{"$gt"',
  "'password':{'$gt'",
  //,
  "}, { username : /.*/ }",
  "username : /.*/",
  "username=%s",
  "username[$regex]",
  'username["$regex"]',
  "username['$regex']",
  'username:{"$regex"',
  "username:{'$regex'",
  '"username":{"$regex"',
  "'username':{'$regex'",
  "username[$ne]",
  'username["$ne"]',
  "username['$ne']",
  'username:{"$ne"',
  "username:{'$ne'",
  '"username":{"$ne"',
  "'username':{'$ne'",
  "username[$gt]",
  'username["$gt"]',
  "username['$gt']",
  'username:{"$gt"',
  "username:{'$gt'",
  '"username":{"$gt"',
  "'username':{'$gt'",
  //,
  "[$or] = [ {}, {",
  "['$or'] = [ {}, {",
  '["$or"] = [ {}, {',
  "$or: [ {}, {",
  '"$in": []',
  "'$in': []",
  "[$in]=[]",
  "['$in']=[]",
  '["$in"]=[]',
  "} ], $comment:",
  //,
  ".insert(",
  ".emit(",
  ".match(",
  "sleep(0",
  "sleep(1",
  "sleep(2",
  "sleep(3",
  "sleep(4",
  "sleep(5",
  "sleep(6",
  "sleep(7",
  "sleep(8",
  "sleep(9",
  ";sleep",
  "&sleep",
  "sleep 0",
  "sleep 1",
  "sleep 2",
  "sleep 3",
  "sleep 4",
  "sleep 5",
  "sleep 6",
  "sleep 7",
  "sleep 8",
  "sleep 9",
  "print(",
  "printf",
  "while(",
  "do{",
  ".foreach(",
  ".map(",
  ";var",
  ";let",
  //,
  "|| 1==1",
  "|| 1==1//",
  "|| 1==1%00",
  "|| true%00",
  "|| true//",
  //,
  "child_process",
  "require(",
  ";return",
  "return;",
  "fetch(",
  "global.process",
  //,
  "/etc/passwd",
  "whoami",
  "../../..",
  "cmd|",
  //,
  "onkeypress",
  //,
  "1' ORDER BY 1",
  "';create table persistent (data",
] as const;

export type TKeywords = typeof DefaultKeywords[number];

export const Keywords = MirrorWord().add(DefaultKeywords).words;
